name: polychrom-hoomd
channels:
    - conda-forge
dependencies:
    - pip
    - python<3.11
    - numpy<1.24
    - scipy>=0.16
    - matplotlib>=2.0
    - pandas>=0.19
    - hoomd=3.11=*gpu*
    - fresnel>=0.13
    - gsd==2.9
    - joblib
    - pyside2
    - ipython
    - notebook
    - pip:
        - git+https://github.com/open2c/polykit.git
        - git+https://github.com/open2c/cooltools.git
        - git+https://github.com/mtortora/lattice-translocators.git
